ALTER TABLE tutors 
ADD COLUMN phone VARCHAR(255),
ADD COLUMN city VARCHAR(255),
ADD COLUMN about VARCHAR(255),
ADD COLUMN image VARCHAR(255),
ADD COLUMN role_id BIGINT NOT NULL,
ADD CONSTRAINT FOREIGN KEY(role_id) REFERENCES roles(id);
